[package]
name = "cauchy-crypto"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
blake3 = "0.3.3"
digest = "0.8.1"
minisketch-rs = "0.1.9"
oddsketch = { git = "https://github.com/hlb8122/oddsketch-rs" }

[dev-dependencies]
hex = "0.4.2"
