[package]
name = "cauchy-common"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
crypto = { package = 'cauchy-crypto', path = '../cauchy-crypto' }

bytes = "0.5.4"
