[package]
name = "cauchy-network"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.4"
tokio = { version = "0.2.11", features = ["dns", "io-util", "tcp"] }
tokio-util = { version = "0.2.0", features = ["codec"] }

[dev-dependencies]
rand = "0.7.3"
