[package]
name = "cauchy-network"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.4"
futures = "0.3.4"
tokio = { version = "0.2.20", features = ["dns", "io-util", "stream", "tcp"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
tokio-tower = "0.3.6"
tower-service = "0.3.0"
pin-project = "0.4.9"

[dev-dependencies]
rand = "0.7.3"
