[package]
name = "cauchy-vm"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>", "Chris Novick <c.r.novick@pm.me>"]
edition = "2018"

[dependencies]
bytes = "0.5.4"
rust-wasm = {git="https://github.com/TheRealBluesun/rust-wasm", tag="v0.1.2"}
digest = "0.8.1"
rayon = "1.3.0"

[dev-dependencies]
hex = "0.4.2"
sha2 = "0.8.1"
blake3 = "0.3.3"
