[package]
name = "cauchy-arena"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
consensus = { package = 'cauchy-consensus', path='../cauchy-consensus' }

bytes = "0.5.4"
parking_lot = "0.10.0"
rand = "0.7.3"
